// https://www.npmjs.com/package/swagger-autogen
// npm run swagger-autogen
const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'TalentGift Rest API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:5000', 
  schemes: ['http'], 
};

const outputFile = '../docs/swagger-output.json'
const endpointsFiles = ['./server.js', './routes/surveys.js', './routes/resetPassword', 
    './routes/signUp.js', './routes/signIn.js', './routes/organization',
    './routes/members.js','./routes/links.js','./routes/reports.js','./routes/profile.js']
swaggerAutogen(outputFile, endpointsFiles, doc)